### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by serycjon** [henghuiding/MOSE#1]
Hi,
you have a wrong link on the web. Section: downloads - "Dataset" links to this repo, instead of https://github.com/henghuiding/MOSE-api (the dataset icon has the correct link).
([here](https://github.com/henghuiding/MOSE/blob/5e8e97d9b4c9c298e106658721ba2f099bcde699/index.html#L347))

**Comment by henghuiding** [comment]
Hi,
Thank you very much for your kind reminder! have updated it.
